"""add_retweet_type_and_retweeted_tweet_id_to_tweets

Revision ID: 9062ba4a7a43
Revises: 7356f32a0179
Create Date: 2025-12-07 18:35:13.958114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9062ba4a7a43'
down_revision: Union[str, None] = '7356f32a0179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('retweet_type', sa.String(length=10), nullable=True))
    op.add_column('tweets', sa.Column('retweeted_tweet_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tweets_retweeted_tweet_id'), 'tweets', ['retweeted_tweet_id'], unique=False)
    op.create_foreign_key(None, 'tweets', 'tweets', ['retweeted_tweet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_index(op.f('ix_tweets_retweeted_tweet_id'), table_name='tweets')
    op.drop_column('tweets', 'retweeted_tweet_id')
    op.drop_column('tweets', 'retweet_type')
    # ### end Alembic commands ###
