"""remove_retweet_functionality

Revision ID: b6a29bdfc0ed
Revises: 9062ba4a7a43
Create Date: 2025-12-07 18:59:42.314370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a29bdfc0ed'
down_revision: Union[str, None] = '9062ba4a7a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retweets_tweet_id'), table_name='retweets')
    op.drop_index(op.f('ix_retweets_user_id'), table_name='retweets')
    op.drop_table('retweets')
    op.drop_index(op.f('ix_tweets_retweeted_tweet_id'), table_name='tweets')
    op.drop_constraint(op.f('tweets_retweeted_tweet_id_fkey'), 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'retweeted_tweet_id')
    op.drop_column('tweets', 'retweet_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('retweet_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('tweets', sa.Column('retweeted_tweet_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tweets_retweeted_tweet_id_fkey'), 'tweets', 'tweets', ['retweeted_tweet_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tweets_retweeted_tweet_id'), 'tweets', ['retweeted_tweet_id'], unique=False)
    op.create_table('retweets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tweet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], name=op.f('retweets_tweet_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('retweets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('retweets_pkey')),
    sa.UniqueConstraint('user_id', 'tweet_id', name=op.f('uq_retweets_user_tweet'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_retweets_user_id'), 'retweets', ['user_id'], unique=False)
    op.create_index(op.f('ix_retweets_tweet_id'), 'retweets', ['tweet_id'], unique=False)
    # ### end Alembic commands ###
